name:                cotoami-spec
version:             0.1.0.0
github:              "marubinotto/cotoami-spec"
license:             BSD3
author:              "Daisuke Morita"
maintainer:          "daisuke.marubinotto@gmail.com"
copyright:           "2019 Daisuke Morita"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/marubinotto/cotoami-spec#readme>

dependencies:
- base >= 4.7 && < 5
- QuickCheck
- hspec
- webdriver
- lifted-base
- transformers
- data-default
- text
- HUnit
- aeson
- hspec-core

library:
  source-dirs: src

executables:
  cotoami-spec-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - cotoami-spec

tests:
  cotoami-spec-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - cotoami-spec
