version: 2
jobs:
  run-spec:
    machine: true
    steps:
      - checkout
      - run:
          name: Install stack
          command: curl -sSL https://get.haskellstack.org/ | sh
      - run:
          name: Run spec
          command: ./run-spec-with-docker.sh
workflows:
  version: 2
  run-spec:
    jobs:
      - run-spec
