version: 2
jobs:
  run-spec:
    machine: true
    environment:
      IMAGE_NAME: "cotoami/cotoami-elixir:1.7"
    steps:
      - checkout
      - run:
          name: Run spec
          command: ./run-spec-with-docker.sh
workflows:
  version: 2
  run-spec:
    jobs:
      - run-spec
